---

# Private Topology
- name: Copy NGINX-ingress values file - private
  when: private_topology
  copy:
    src: files/values-nginx-ingress.yaml
    dest: /tmp/values-nginx-ingress.yaml
    mode: 0700
    owner: admin
    group: admin

- name: Check to see if nginx-ingress already exist - private
  when: private_topology
  shell: "helm ls | grep nginx-ingress"
  become: admin
  register: nginx_result
  changed_when: nginx_result.rc == 1
  failed_when: nginx_result.rc not in [0,1]
  ignore_errors: yes

- name: Install nginx-ingress via helm - private
  shell: helm install --name nginx-ingress --namespace kube-public -f /tmp/values-nginx-ingress.yaml stable/nginx-ingress --version 1.6.4
  become: admin
  ignore_errors: yes
  when: private_topology and nginx_result.rc == 1

- name: Upgrade nginx-ingress via helm - private
  shell: helm upgrade nginx-ingress --namespace kube-public -f /tmp/values-nginx-ingress.yaml stable/nginx-ingress --version 1.6.4
  become: admin
  ignore_errors: yes
  when: private_topology and nginx_result.rc == 0


# Cleanup
- name: Cleanup
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /tmp/values-nginx-ingress.yaml
