---

# Private Topology
- name: Download helm
  when: private_topology
  unarchive:
    src: https://kubernetes-helm.storage.googleapis.com/helm-v2.14.0-linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy helm binary file - private
  when: private_topology
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
    mode: 0740
    owner: admin
    group: admin

- name: Create tiller service account - private
  when: private_topology
  shell: kubectl create serviceaccount --namespace kube-system tiller
  become: admin
  ignore_errors: yes

- name: Initiate tiller service account and upgrade it - private
  when: private_topology
  shell: helm init --service-account tiller --upgrade
  become: admin

- name: Create cluster role binding rule - private
  when: private_topology
  shell: kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
  become: admin
  ignore_errors: yes


# Public Topology
- name: Download helm
  when: not private_topology
  unarchive:
    src: https://kubernetes-helm.storage.googleapis.com/helm-v2.14.0-linux-amd64.tar.gz
    dest: /ops/manifests/
    remote_src: yes

- name: Copy helm binary file - public
  when: not private_topology
  copy:
    src: /ops/manifests/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: 0740

- name: Create tiller service account - public
  when: not private_topology
  shell: kubectl create serviceaccount --namespace kube-system tiller
  ignore_errors: yes

- name: Initiate tiller service account and upgrade it - public
  when: not private_topology
  shell: helm init --service-account tiller --upgrade
  become: admin

- name: Create cluster role binding rule - public
  when: not private_topology
  shell: kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
  become: admin
  ignore_errors: yes


# Wait
- name: Wait for 1 minute to allow tiller pod to get ready
  pause: minutes=1
