---

# Public Topology
- name: Copy fluent-bit values file - public
  when: not private_topology
  copy:
    src: files/values-fluent-bit.yaml
    dest: /ops/manifests/values-fluent-bit.yaml

- name: Check to see if fluent-bit already exist - public
  when: not private_topology
  shell: "helm ls | grep fluent-bit"
  register: fb_result
  changed_when: fb_result.rc == 1
  failed_when: fb_result.rc not in [0,1]
  ignore_errors: yes

- name: Install fluent-bit via helm - public
  shell: helm install --name fluent-bit --namespace elastic-stack -f /ops/manifests/values-fluent-bit.yaml stable/fluent-bit --version 2.0.0
  ignore_errors: yes
  when: not private_topology and fb_result.rc == 1

- name: Upgrade fluent-bit via helm - public
  shell: helm upgrade -f /ops/manifests/values-fluent-bit.yaml fluent-bit stable/fluent-bit --version 2.0.0
  ignore_errors: yes
  when: not private_topology and fb_result.rc == 0


# Cleanup
- name: Cleanup
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /ops/manifests/values-fluent-bit.yaml