---

# Private Topology
- name: Copy fluent-bit values file - private
  when: private_topology
  copy:
    src: files/values-fluent-bit.yaml
    dest: /tmp/values-fluent-bit.yaml
    mode: 0700
    owner: admin
    group: admin

- name: Check to see if fluent-bit already exist - private
  when: private_topology
  shell: "helm ls | grep fluent-bit"
  become: admin
  register: fb_result
  changed_when: fb_result.rc == 1
  failed_when: fb_result.rc not in [0,1]
  ignore_errors: yes

- name: Install fluent-bit via helm - private
  shell: helm install --name fluent-bit --namespace elastic-stack -f /tmp/values-fluent-bit.yaml stable/fluent-bit --version 2.0.0
  become: admin
  ignore_errors: yes
  when: private_topology and fb_result.rc == 1

- name: Upgrade fluent-bit via helm - private
  shell: helm upgrade -f /tmp/values-fluent-bit.yaml fluent-bit stable/fluent-bit --version 2.0.0
  become: admin
  ignore_errors: yes
  when: private_topology and fb_result.rc == 0


# Cleanup
- name: Cleanup
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /tmp/values-fluent-bit.yaml