---
- name: Download Kops binaries
  get_url:
    url: https://github.com/kubernetes/kops/releases/download/1.14.0-alpha.2/kops-linux-amd64
    dest: /usr/local/bin/kops
    owner: root
    group: root
    mode: 0755
    force: yes
  become: true